### ISSUE TITLE
The repository is still nothing,

### ISSUE THREAD

**Issue by longtsing** [mkheck/SpringBootUpAndRunning#4]

**Comment by mkheck** [comment]
Hi @longtsing, all code is in the repository for all chapters. To access code for each chapter, you must check out the appropriate branch for that chapter and its beginning (if you wish to code along) or its end state (if you wish to run the complete code). Instead of the master branch, please refer to the appropriate branch. Thanks.

**Comment by longtsing** [comment]
Thanks.I see the code of each chapter in branchs. Why do not  merge it to the master branch? It is confused for beginners.
